### ISSUE TITLE
Не отправляются файлы в групповой чат из обработки 1С

### ISSUE THREAD

**Issue by zakharzv** [green-api/whatsapp-1c-example#18]
Ошибка в процедуре **ВыбратьФайлДляОтправкиСервер**

### Ошибка тут
Ответ = ОбработкаОбъект().ОтправитьВидеоАудиоИзображениеДокумент(**_ПараметрИдЧата_**, ИмяВременногоФайла, ОтправкаТекстСообщения);

### Должно быть так
Ответ = ОбработкаОбъект().ОтправитьВидеоАудиоИзображениеДокумент(**_ПараметрИдГруппы_**, ИмяВременногоФайла, ОтправкаТекстСообщения);

**Comment by AknurKh** [comment]
@zakharzv Здравствуйте!
Ошибки нет. Под параметром ID чата имеется ввиду, что чат может быть и личным (обычным номером собедника) и группой. 
Вы можете вписать туда и обычный номер и идентификатор группы.

**Comment by zakharzv** [comment]
@AknurKh Здравствуйте!

1. На форме при выборе типа чата "Групповой" доступен для заполнения реквизит формы "_**ПараметрИдГруппы**_" и при изменении этого реквизита в реквизите "_**ПараметрИдЧата**_" (который передается для отправки) остается номер телефона. Возможно не хватает обработчика изменения идентификатора группы...
2. Да и по коду видно, что-то не так... В процедуре отправки текстового сообщения "ОтправитьСообщениеWhatsApp" для отправки в группу используется реквизит "_**ПараметрИдГруппы**_". В процедуре отправки файла "ВыбратьФайлДляОтправкиСервер" для отправки в группу используется реквизит "_**ПараметрИдЧата**_". Где то явно ошибка ;)
<img width="601" alt="image" src="https://github.com/green-api/whatsapp-api-client-1c/assets/82809277/e8bf7107-682e-4fe6-80c2-3df9a1c7a7d4">
<img width="818" alt="image" src="https://github.com/green-api/whatsapp-api-client-1c/assets/82809277/526c2c75-5a61-40d9-8079-c4937193a528">

**Comment by AknurKh** [comment]
@zakharzv Спасибо за подробное объяснение!
Проанализировали и действительно нашли ошибку. Передали разработчикам на исправление. 
Сами методы обработки работают нормально
